spring.application.name=learning-assessment-backend
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/learning_assessment_db
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.com.screening=DEBUG
logging.level.org.springframework.data.mongodb=INFO
